### change light color, will turn the lights on if they where off
PUT http://esp:80/lights HTTP/1.1
Content-Type: text/plain
User-Agent: rewards-integration

12

###
# The number is the id that would normally be sent over to the esp over a serial connection

### Turn the lights off
DELETE http://esp:80/lights HTTP/1.1
Content-Type: text/plain

### Turn the ligths on
POST http://esp:80/lights HTTP/1.1
Content-Type: text/plain


### post bodies are hard on the ESP, we're using get requests
### change light color, will turn the lights on if they where off
GET http://esp:80/lights/{num} HTTP/1.1

###
# The number is the id that would normally be sent over to the esp over a serial connection

### Turn the lights off
GET http://esp:80/lights/off HTTP/1.1

### Turn the ligths on
GET http://esp:80/lights/on HTTP/1.1
